language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: TacqfFimLjMg6Rrvjt8/xr7geQTX0kFPuHqV+LfYM4Q9jpD9q++T4E2ez6VctkoWqmgmW4z3OcqvjCKxbE92j5HyR65AymlC76h/YakglrCWUYADLuhTfe89LvxcR523hCiNTjsjn/SxKxcOlVwz3jbYSJOuIWrK6Y61tppzgzSvqjiVly7cBrdhUBh9kN6ijYjP1npP3GM36Nc6vBAYpQ0oKiyuxp0+hzJewYVEVz4xkLzsipT/smsdVtS12Ezwi9CcUtlx7X4J1pSsh2Y/1enD4aNbip8sqhgmN6vElHBiB+h6X13XDloxfaX59oo5dt9cSpLlLb3uQf+CIN1dbCu1tL69MZeb0LL1vL4PQLzbQUz9vlEz+N1BEVDWxo+xbctnafTLsYfjLOeyGnM+mlJbItaKmZ+qMPejnhtWSFzRwVuqd0Dkn5aJVlMUEtGTYo1nUpp8c/7ZZ9rq+A6FaXJtO3I/IaRe6mwwiDXvrx1nJBRg7+oSTiBNDK2pmI5NGW3giHuLPouUOAfMZdPC8uY2Xmg7fpnur+dPdGEoBmkuiiEvDAHHpELhBp6BXYVxp5iO6BKOurc3i3nJrXPXf4FFjZ9x5jejsUywIidjo08S9UblBadX+tUFSbknKVOnhTOQ9yVmv35fueIMbEAMS06lazLyQFJmwZ3ZuLj1E4w=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
